# Ejercicios NumPy

In [3]:
import numpy as np

lista_de_listas = [[-44, 12], [12.0, 51], [1300, -5.0]]
a = np.array(lista_de_listas)

print("Matriz original")
print(a)

Matriz original
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]


## 1.  Restarle 5 a la fila 2 de la matriz

In [4]:
#IMPLEMENTAR
a[1:] -= 5
print(a)

[[ -44.   12.]
 [   7.   46.]
 [1295.  -10.]]


## 2. Multiplicar por 2 toda la matriz

In [5]:
#IMPLEMENTAR
a *= 2
print(a)

[[ -88.   24.]
 [  14.   92.]
 [2590.  -20.]]


## 3. Dividir por -5 las dos primeras filas de la matriz

In [ ]:
#IMPLEMENTAR
a[.2] /= 5
print(a)

## 4. Imprimir la ultima fila de la matriz

In [6]:
ultima_fila=a[-1]
# IMPLEMENTAR
print(ultima_fila)

[2590.  -20.]


## 5. Calcular la suma de los elementos de **a** utilizando dos ciclos **for** anidados


In [7]:
suma = 0
for i in a:
    suma += sum(i)
#IMPLEMENTAR
print(suma)

2612.0


## 6. Calcular la suma de los elementos de a utilizando **np.sum**

In [ ]:
suma = 0 
#IMPLEMENTAR
print(suma)

## 7. Calcular el promedio de los elementos de las primeras dos filas de a utilizando dos fors anidados

In [18]:
promedio=0
#IMPLEMENTAR
b = a[:2]
contador = 0
suma=0
for fila in b:
    for dato in fila:
        suma += dato
        contador += 1
promedio = suma / contador

print(suma / promedio)

4.0


## 8. Calcular el promedio de los elementos de las primeras dos filas de utilizando slices y **np.mean**


In [16]:
promedio=0
promedio = np.mean(a[:2])
#IMPLEMENTAR
print(promedio)

10.5
