# Numpy

Numpy es el **paquete más básico pero poderoso** para la computación científica y la manipulación de datos en Python. **Nos permite trabajar con matrices y matrices multidimensionales**.

La mayoría de las otras bibliotecas que se usan en el análisis de datos con Python, como scikit-learn , SciPy y Pandas usan algunas de las características de NumPy.

[Sitio oficial](https://numpy.org/)

## Instalación

En una consola o terminal, ejecutar el siguiente comando:
```bash
pip install numpy
```

## Importar NumPy a nuestro código

In [1]:
import numpy as np

## Arreglos

Los **arreglos (vectores)** son listas de una o más dimensiones donde sus **_elementos son del mismo tipo (usualmente numérico)_**.

In [3]:
a = np.array([10,20,30])

print([10,20,30])
print(a)

[10, 20, 30]
[10 20 30]


Consultar el tipo de dato

In [4]:
print(type(a)) 

<class 'numpy.ndarray'>


Consultar el tamaño del array

In [5]:
print(a.shape)

(3,)


Extraer información del array

In [6]:
print(a[0], a[1], a[2], sep="\n")

10
20
30


Modificar posiciones del array

In [7]:
a[0] = 5

print(a)

[ 5 20 30]


## Matrices
los arreglos de dos dimensiones lo llamamos **matrices**.

In [8]:
b = np.array([[10,20,30],[40,50,60]])

print(b)

[[10 20 30]
 [40 50 60]]


Consultar el tipo de dato

In [9]:
print(type(a)) 

<class 'numpy.ndarray'>


Consultar el tamaño de la matriz

In [11]:
print(b.shape)

(2, 3)


Extraer información de la matriz

In [12]:
print(b[0], b[1], sep="\n")

[10 20 30]
[40 50 60]


In [13]:
print(b[0][0], b[1][1], sep="\n")

10
50


Modificar posiciones de la matriz

In [14]:
b[0][0] = 5
b[1][1] = 10

print(b)

[[ 5 20 30]
 [40 10 60]]


## Creación de matrices con NumPy
La biblioteca también proporciona muchas funciones para crear matrices:

In [16]:
# Matriz de ceros
matriz = np.zeros((4,3), dtype=np.int32) #filas y columnas

print(matriz)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
# Matriz de unos
matriz = np.ones((4,3))

print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Crear una matriz constante
matriz = np.full((2,6), 5.01)

print(matriz)

[[5.01 5.01 5.01 5.01 5.01 5.01]
 [5.01 5.01 5.01 5.01 5.01 5.01]]


In [21]:
# Crear una matriz de identidad
matriz = np.eye(7)

print(matriz) 

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [23]:
# Crear una matriz a partir de los valores de la diagonal
matriz = np.diag([1, 2, 3, 4, 5.1, 6])

print(matriz)

[[1.  0.  0.  0.  0.  0. ]
 [0.  2.  0.  0.  0.  0. ]
 [0.  0.  3.  0.  0.  0. ]
 [0.  0.  0.  4.  0.  0. ]
 [0.  0.  0.  0.  5.1 0. ]
 [0.  0.  0.  0.  0.  6. ]]


In [24]:
# Crear una matriz llena de valores aleatorios
matriz = np.random.random((3,4))

print(matriz)

[[0.66378101 0.11835263 0.91493034 0.52878523]
 [0.26738247 0.76402835 0.77464643 0.9042904 ]
 [0.31606199 0.07290925 0.42870673 0.00483799]]


Puede leer sobre otros métodos de creación de matrices en la documentación de Numpy

https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation

## Indexación de matrices

NumPy ofrece varias formas de indexar en matrices.

### Indexación entera (rebanar / slice)

Similar a las listas de Python, las matrices NumPy se pueden cortar. Dado que las matrices pueden ser multidimensionales, debe especificar un segmento para cada dimensión de la matriz:

In [25]:
a = np.array([[1,2,3], [5,6,7], [9,10,11]])

print(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


Voltear las entradas en cada fila en la dirección izquierda / derecha. Las columnas se conservan, pero aparecen en un orden diferente al anterior.

In [26]:
print(a)
print()
print(np.fliplr(a))

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 3  2  1]
 [ 7  6  5]
 [11 10  9]]


Usar el rebanado para sacar el subconjunto que consiste en las 2 primeras filas y las columnas 1 y 2

In [27]:
b = a[:2, 1:3]

print(b)

[[2 3]
 [6 7]]


Una rebanada de una matriz es una vista en los mismos datos, por lo que modificará la matriz original.

In [28]:
print(b)
# b[0, 0] es la misma pieza de datos que a[0, 1]
b[0, 0] = 77 

print()
print(b)
print()
print(a)

[[2 3]
 [6 7]]

[[77  3]
 [ 6  7]]

[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]


También puede mezclar la indexación de enteros con la indexación de sectores. Sin embargo, al hacerlo, se obtendrá una matriz de rango más bajo que la matriz original.

In [29]:
row_r1 = a[1]               # Solo la fila como un array
print(row_r1, row_r1.shape)
row_r2 = a[1:2]             # Una matriz de la fila
print(row_r2, row_r2.shape)

[5 6 7] (3,)
[[5 6 7]] (1, 3)


In [30]:
col_r1 = a[:, 1]            # Solo la columna
print(col_r1, col_r1.shape) 
col_r2 = a[:, 1:2]          #Una matriz de la columna
print(col_r2, col_r2.shape) 

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


Cuando indexa matrices de números utilizando la división, la vista de matriz resultante siempre será una submatriz de la matriz original. Por el contrario, la indexación de matrices de enteros le permite construir matrices arbitrarias utilizando los datos de otra matriz.

In [31]:
print(a)

[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]


In [32]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 6 9]


In [33]:
print(a[[0, 1, 2], [0, 1, 0]])  

[1 6 9]


### Indexación booleana
La indexación de matriz booleana le permite seleccionar elementos arbitrarios de una matriz. Con frecuencia, este tipo de indexación se utiliza para seleccionar los elementos de una matriz que satisfacen alguna condición. Aquí hay un ejemplo:

In [ ]:
print(a)

In [51]:
bool_idx = a % 2 == 1

print(bool_idx)

[[ True  True  True]
 [ True False  True]
 [ True False  True]]


In [52]:
print(a[bool_idx])

[ 1 77  3  5  7  9 11]


In [43]:
print(a[a > 20])

[77]


Por brevedad, hemos omitido muchos detalles sobre la indexación de matrices numpy; si quieres saber más debes leer la documentación .  

https://numpy.org/doc/stable/reference/arrays.indexing.html

## Tipos de datos

Cada matriz numpy es una cuadrícula de elementos del mismo tipo. Numpy proporciona un gran conjunto de tipos de datos numéricos que puede utilizar para construir matrices. Numpy intenta adivinar un tipo de datos cuando crea una matriz, pero las funciones que construyen matrices generalmente también incluyen un argumento opcional para especificar explícitamente el tipo de datos. Aquí hay un ejemplo:

In [57]:
x = np.array([1, 2], dtype=np.int8)
print(x.dtype)

int32


In [54]:
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [55]:
x = np.array([1, 2], dtype=np.int64) #hasta q nuemro se almacena en un entero
print(x.dtype)

int64


In [60]:
var = x[0]
print(var, type(var))

1 <class 'numpy.int32'>


Puede leer todo sobre numerosos tipos de datos en la documentación .

https://numpy.org/doc/stable/reference/arrays.dtypes.html

## Matemáticas en matrices

Las funciones matemáticas básicas operan por elementos en matrices y están disponibles como sobrecargas de operador y como funciones en el módulo NumPy:

In [61]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


Suma de elementos de matrices cuadradas, producen una matriz cuadrada con la suma de los elementos en cada posición.

In [62]:
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [63]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


Resta (diferencia) de elementos de matrices cuadradas, producen una matriz cuadrada con la diferencia de los elementos en cada posición.

In [64]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [65]:
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [66]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


Multiplicación (producto) de elementos de matrices cuadradas, producen una matriz cuadrada con el producto de los elementos en cada posición.

In [67]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [68]:
print(x * y)

[[ 5. 12.]
 [21. 32.]]


In [69]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


Tenga en cuenta que _es una multiplicación_ por elementos, no una _multiplicación de matrices_. En cambio, usamos la función **dot** para calcular productos internos de vectores, para multiplicar un vector por una matriz y para multiplicar matrices.

In [70]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [71]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [ ]:
print(np.dot(x, y))

In [72]:
print(np.cross(x, y))#hacer matrices pequeñas


[-4. -4.]


División de elementos de matrices cuadradas, producen una matriz cuadrada con el cociente de los elementos en cada posición.

In [73]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [74]:
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.divide(x, y))

Aplicar funciones sobre una matriz, aplica la función a cada una de las posiciones de la matriz

In [75]:
print(x)

[[1. 2.]
 [3. 4.]]


In [76]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [77]:
print(np.sin(x))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


Numpy proporciona muchas funciones útiles para realizar cálculos en matrices; uno de los más útiles es sum:

In [78]:
print(x)

[[1. 2.]
 [3. 4.]]


In [79]:
# Calcular la suma de todos los elementos
print(np.sum(x))

# Calcula la suma de cada columna
print(np.sum(x, axis=0))

# Calcula la suma de cada fila
print(np.sum(x, axis=1))

10.0
[4. 6.]
[3. 7.]


Puede encontrar la lista completa de funciones matemáticas proporcionadas por numpy en la documentación.

https://numpy.org/doc/stable/reference/routines.math.html

## Operaciones de matrices

### Transposición de una matriz o matriz traspuesta
Para transponer una matriz, simplemente use el **T** atributo de un objeto de matriz:

In [83]:
z = np.array([1,2,3],[5,6,7],[9,10,11])
print(z)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [84]:
print(z.T)

NameError: name 'z' is not defined

Numpy proporciona muchas más funciones para manipular matrices; puedes ver la lista completa en la documentación.
https://numpy.org/doc/stable/reference/routines.array-manipulation.html

In [85]:
inv = np.linalg.inv(z)
print(inv)

NameError: name 'z' is not defined

In [86]:
np.dot(z,inv)

NameError: name 'z' is not defined